apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myapp
spec:
  hosts:
  - myapp.com
  gateways:
  - myapp-gateway
  http:
  - name: myapp-v2
    route:
    - destination:
        host: myapp.com
        subset: v2
   - name: myapp-v1
     route:
     - destination:
          host: myapp.com
          subset: vi

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
   name: myapp-destination
spec:
  host: myapp.com
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
       version: v2
